"""v0.4 v0.5 embeddings idempotency rbac

Revision ID: a9a8b26bb922
Revises: 1b07d72efc28
Create Date: 2026-04-25 20:59:35.008897+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a9a8b26bb922'
down_revision = '1b07d72efc28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'entity_type', 'entity_id', 'model', name='uq_embeddings_entity_model')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_team_entity', ['team_id', 'entity_type'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('response_content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'key', name='uq_idempotency_team_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_expires', ['expires_at'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', name='uq_membership_api_key')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_membership_team_role', ['team_id', 'role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_team_role')

    op.drop_table('memberships')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_expires')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_team_entity')

    op.drop_table('embeddings')
    # ### end Alembic commands ###
